name: wordpress-project

networks:
  wordpress:
    driver: bridge

volumes:
  app:             
  my:               

services:
  database:
    image: mysql:8.0.30 
    networks:
      - wordpress
    environment:
      MYSQL_ROOT_PASSWORD: ifpb
      MYSQL_DATABASE: wordpress
      MYSQL_USER: aluno
      MYSQL_PASSWORD: ifpb
    volumes:
      - my:/var/lib/mysql  
    restart: unless-stopped

  webserver:
    image: wordpress:latest
    networks:
      - wordpress
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: aluno
      WORDPRESS_DB_PASSWORD: ifpb 
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - app:/var/www/html 
    depends_on:
      - database
    restart: unless-stopped

 
  webproxy:
    image: anajulita/nginx-wordpress-lb:latest
    networks:
      - wordpress
    ports:
      - "8080:8080"  
    depends_on:
      - webserver
    restart: unless-stopped
